services:
  db:
    container_name: lm_db
    image: ankane/pgvector:latest
    volumes:
      - ./database/data:/var/lib/postgresql
    env_file:
      - ./database/.env
    ports:
      - "8001:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 2
    networks:
      - fast_api

networks:
  fast_api:
    driver: bridge